GET http://localhost:4000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7fSwiaWF0IjoxNzM4MzEyNDY4LCJleHAiOjE3MzgzMTI0ODN9.aUPrOk4Cmgl_9Wq77FtkKU2-lSgJFjpxieXQPRvXVPY

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzgzMTI0MDR9.vT31cdt402vb20ptdLiufqotP_1i9a2G2bbgjmYnhPc"
}

###
POST http://localhost:3000/login

Content-Type: application/json
{
    "username": "tarun didwaniya"
}
